export {};
declare global { interface Window { stockPet: {
  identity(): Promise<Record<string,string>>;
  session(): Promise<any>;
  login(credentials: { email: string; password: string }): Promise<{ok:true;session:any}|{ok:false;error:{code:string;status:number}}>;
  logout(): Promise<any>;
  api(path: string, options?: { method?: string; body?: unknown }): Promise<any>;
  openLogin(): Promise<void>;
  openControl(panel?:string): Promise<void>;
  setAlwaysOnTop(enabled:boolean):Promise<void>;
  setLaunchAtLogin(enabled:boolean):Promise<void>;
  setWindowSize(size:"small"|"medium"|"large"):Promise<void>;
  setOpacity(value:number):Promise<void>;
  setPositionLocked(value:boolean):Promise<void>;
  getSystemSettings():Promise<{alwaysOnTop:boolean;launchAtLogin:boolean}>;
  getActionPreferences():Promise<any>;
  saveActionPreferences(value:unknown):Promise<any>;
  getCustomStateAssets():Promise<Record<string,string>>;
  chooseCustomGif(state:string):Promise<Record<string,string>>;
  clearCustomGif(state:string):Promise<Record<string,string>>;
  getCustomRuleAssets():Promise<Record<string,string>>;
  chooseCustomRuleGif(symbol:string,ruleId:string):Promise<Record<string,string>>;
  clearCustomRuleGif(symbol:string,ruleId:string):Promise<Record<string,string>>;
  getCustomRuleAudioAssets():Promise<Record<string,string>>;
  chooseCustomRuleAudio(symbol:string,ruleId:string):Promise<Record<string,string>>;
  clearCustomRuleAudio(symbol:string,ruleId:string):Promise<Record<string,string>>;
  onCustomAssetsChanged(handler:(assets:Record<string,string>)=>void):()=>void;
  onCustomRuleAssetsChanged(handler:(assets:Record<string,string>)=>void):()=>void;
  onCustomRuleAudioAssetsChanged(handler:(assets:Record<string,string>)=>void):()=>void;
  onActionPreferencesChanged(handler:(preferences:any)=>void):()=>void;
  showContextMenu():Promise<void>;
  onQuickAction(handler:(action:string)=>void):()=>void;
  onSessionChanged(handler:(session:any)=>void):()=>void;
  checkUpdates():Promise<{status:string}>;
  installUpdate():Promise<void>;
  onUpdateStatus(handler:(status:string)=>void):()=>void;
  hide():Promise<void>;
  quit():Promise<void>;
} } }
